# Generated by Django 4.2.13 on 2025-11-20 06:29

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaMaquinaria',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'alertas_maquinaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asig', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asig', models.DateField(db_column='fecha_asig')),
                ('fin_asig', models.DateField(blank=True, db_column='fin_asig', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('foto_finalizada', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_finalizacion')),
            ],
            options={
                'db_table': 'asignacion',
                'ordering': ['-fecha_asig'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoMaquina',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'status_maq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maq', models.AutoField(primary_key=True, serialize=False)),
                ('equipo', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('ult_mant', models.DateField(blank=True, null=True)),
                ('consu_combus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'maquinaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusAsignacion',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Asignación',
                'verbose_name_plural': 'Estados de Asignaciones',
                'db_table': 'status_asig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=100)),
                ('apellido_pat', models.CharField(max_length=100)),
                ('apellido_mat', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('fec_init', models.DateField()),
                ('usuario', models.CharField(max_length=100)),
                ('contra', models.CharField(max_length=100)),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webApp_trabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id_afp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'afp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'banco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistritoResidencia',
            fields=[
                ('id_distrito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'distrito_residencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id_privilegio', models.AutoField(primary_key=True, serialize=False)),
                ('privilegio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'privilegios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusCapacitacion',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'webApp_statuscapacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusTra',
            fields=[
                ('id_status_tra', models.AutoField(primary_key=True, serialize=False)),
                ('status_tra', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'status_tra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horas', models.IntegerField(default=6)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.asignacion')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrohoras', to='webApp.trabajador')),
            ],
            options={
                'db_table': 'registro_horas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(db_index=True, max_length=50)),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='webApp.asignacion')),
                ('usuario_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_creadas', to='webApp.trabajador')),
            ],
            options={
                'verbose_name': 'Notificación de Evento',
                'verbose_name_plural': 'Notificaciones de Eventos',
                'db_table': 'notificaciones_eventos',
                'ordering': ['-fecha_creacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Dispositivo/Navegador')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.trabajador')),
            ],
            options={
                'verbose_name': 'Historial de Login',
                'verbose_name_plural': 'Historiales de Login',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.CASCADE, to='webApp.statuscapacitacion')),
                ('maquina', models.ForeignKey(blank=True, db_column='id_maq', null=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.maquina')),
                ('trabajador', models.ForeignKey(db_column='id_emp', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='webApp.trabajador')),
            ],
            options={
                'db_table': 'webApp_capacitacion',
                'managed': False,
            },
        ),
    ]
