# Generated by Django 4.2.13 on 2025-11-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capacitacion',
        ),
    ]
