# Generated by Django 4.2.13 on 2025-11-20 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_delete_capacitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.CASCADE, to='webApp.statuscapacitacion')),
                ('maquina', models.ForeignKey(blank=True, db_column='id_maq', null=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.maquina')),
                ('trabajador', models.ForeignKey(db_column='id_emp', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='webApp.trabajador')),
            ],
            options={
                'db_table': 'webApp_capacitacion',
                'managed': True,
            },
        ),
    ]
