# Generated by Django 4.2.13 on 2025-12-11 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webApp', '0005_capacitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_alumno', models.CharField(max_length=20, unique=True)),
                ('carrera', models.CharField(max_length=100)),
                ('anio_egreso', models.IntegerField()),
                ('empresa_actual', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egresado',
                'verbose_name_plural': 'Egresados',
            },
        ),
        migrations.DeleteModel(
            name='AFP',
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='maquina',
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='trabajador',
        ),
        migrations.DeleteModel(
            name='DistritoResidencia',
        ),
        migrations.RemoveField(
            model_name='historiallogin',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario_origen',
        ),
        migrations.DeleteModel(
            name='Privilegio',
        ),
        migrations.RemoveField(
            model_name='registrohoras',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='registrohoras',
            name='trabajador',
        ),
        migrations.DeleteModel(
            name='StatusTra',
        ),
        migrations.DeleteModel(
            name='AlertaMaquinaria',
        ),
        migrations.DeleteModel(
            name='EstadoMaquina',
        ),
        migrations.DeleteModel(
            name='StatusAsignacion',
        ),
        migrations.DeleteModel(
            name='Capacitacion',
        ),
        migrations.DeleteModel(
            name='HistorialLogin',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='RegistroHoras',
        ),
        migrations.DeleteModel(
            name='StatusCapacitacion',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='Maquina',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
