# Generated by Django 4.2.13 on 2025-12-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_egresado_delete_afp_delete_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
