# Generated by Django 4.2.13 on 2025-12-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_egresado_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresado',
            name='apellidos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='egresado',
            name='correo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='egresado',
            name='nombres',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
