# Generated by Django 4.2.13 on 2025-12-11 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_egresado_apellidos_egresado_correo_egresado_nombres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_empleo', models.CharField(max_length=50, verbose_name='Tiempo en conseguir empleo')),
                ('es_relacionado', models.CharField(max_length=2, verbose_name='¿Trabajo relacionado con carrera?')),
                ('calificacion_prep', models.IntegerField(verbose_name='Calificación de la preparación (1-5)')),
                ('competencias', models.TextField(verbose_name='Competencias adicionales necesarias')),
                ('recomendaria', models.CharField(max_length=2, verbose_name='¿Recomendaría la universidad?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('egresado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webApp.egresado')),
            ],
        ),
    ]
